/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_XFILE_H_RPCGEN
#define _RPC_XFILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define STRLENGHT 100

struct Esempio {
	char stringa[STRLENGHT];
};
typedef struct Esempio Esempio;

#define SERVER 0x20000013
#define SERVERVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETSTRINGA 1
extern  Esempio * getstringa_1(void *, CLIENT *);
extern  Esempio * getstringa_1_svc(void *, struct svc_req *);
#define GETSAME 2
extern  int * getsame_1(int *, CLIENT *);
extern  int * getsame_1_svc(int *, struct svc_req *);
extern int server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETSTRINGA 1
extern  Esempio * getstringa_1();
extern  Esempio * getstringa_1_svc();
#define GETSAME 2
extern  int * getsame_1();
extern  int * getsame_1_svc();
extern int server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Esempio (XDR *, Esempio*);

#else /* K&R C */
extern bool_t xdr_Esempio ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_XFILE_H_RPCGEN */
